# Generated by Django 4.0.5 on 2022-07-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFlashCards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='choice',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data',
            name='answer',
            field=models.CharField(max_length=100000),
        ),
    ]
